---
title: "table4_output"
author: "Fonti Kar"
date: "2023-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(APCalign, dplyr, kableExtra, here)
```

### Subset of taxa 

```{r}
testing_taxa <- tibble(taxon = c("Banksia integrifolia", "Acacia aneura", "Commersonia rosea", "Grevillea umbellulata subsp. acerosa", "Fabaceae sp.", "Dryandra sp.", "Athrotaxis laxiflolia", "Galactia striata", "Hibbertia stricta", "Atherosperma moschatum integrifolium", "Argyrodendron Whyanbeel"))
```

### Load resources

```{r}
resources <- load_taxonomic_resources()
```


### Align taxa

Should I add `identifier = c("UNSW")`? Relevant to Fabaceae sp. and Galactia striata

```{r}
# Default options
basic_aligned_output <- align_taxa(testing_taxa$taxon, resources = resources, identifier = c("UNSW"))

# Full table
full_aligned_output <- align_taxa(testing_taxa$taxon, resources = resources, full = TRUE)

```

Default align taxa

```{r}
options(knitr.kable.NA = '')

basic_aligned_output |> 
  kable(align = c(rep("c", 5), rep("l", 2))) |> 
  kable_classic()
```

Full align taxa

```{r}
options(knitr.kable.NA = '')

full_aligned_output |> 
  kable(align = c(rep("c", 5), rep("l", 2))) |> 
  kable_classic(full_width = TRUE) |> 
  column_spec(6, width_min = "10cm") |> 
  column_spec(1:3, width_min = "4cm") |> 
  column_spec(8:24, width_min = "4cm")
```

### Update taxa

```{r}
splits_update_output <- update_taxonomy(basic_aligned_output, resources = resources, taxonomic_splits = TRUE)
```

```{r}
options(knitr.kable.NA = '')

splits_update_output |> 
  kable(align = c(rep("c", 10), 
                  rep("l", 2),
                  "c", "l", "c")) |> 
  kable_classic(full_width = F) |> 
  column_spec(11, width_min = "10cm") |> 
  column_spec(12, width_min = "5cm") |> 
  column_spec(c(1:4, 19), width_min = "3.5cm")
```

### Taxonomic update lookup

```{r}
lookup_output <- create_taxonomic_update_lookup(testing_taxa$taxon, resources = resources)

readr::write_csv(lookup_output, "output/table4_create_taxonomic_update_lookup.csv")
```

```{r}
options(knitr.kable.NA = '')

lookup_output |> 
  kable(align = c(rep("c", 9), 
                  rep("l", 2),
                  "c", "l", "c")) |> 
  kable_classic(full_width = F) |> 
  column_spec(10, width_min = "10cm") |>
  column_spec(1:3, width_min = "3cm") |>
  column_spec(4, width_min = "8cm") |> 
  as_image(width = 5, file = here("output/table4_create_taxonomic_update_lookup.png"),
           zoom = 2)
```

